Attempt to pull from origin and check for errors

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -100,7 +100,19 @@ jobs:
           script: |
             echo "SSH connection established."
             cd /home/ubuntu/html/react-jest/react-redux-login-counter/
-            git pull origin main
+            # Attempt to pull from origin and check for errors
+          
+            if ! git pull origin main; then
+                echo "Error occurred during 'git pull'. Stopping the deployment process."
+                exit 1
+            fi
+            
             npm install
-            npm run build
+
+            # Build the project
+            if ! npm run build; then
+                echo "Build failed. Stopping the deployment process."
+                exit 1
+            fi
+            
             echo "Deployment and server restart (if applicable) completed successfully."
